const GeoLayout celena_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Left),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Right),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Up),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Down),
			GEO_BRANCH(1, celena_Capless_Head_Switch_Option_Capless_Head_Dead),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_2),
			GEO_DISPLAY_LIST(LAYER_ALPHA, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_2),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 60456),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Butt_mesh_layer_5),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 70, -1, 0, celena_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Torso_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 122, -12, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_5),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Half_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Left),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Right),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Up),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Down),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Head_Dead),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Capless_Head),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 53, 0, 75, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Arm_Color_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, celena_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Forearm_mesh_layer_5),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, 28, -21, 25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Wing_DL_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Arm_Color_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 66, 0, 0, celena_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Forearm_mesh_layer_5),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Open),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Peace),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Cap),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_celena_Right_Hand_Wing_Cap),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, -28, 21, -25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Wing_DL_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, 45, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Thigh_Color_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, celena_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 6, 0, celena_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, -46, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Thigh_Color_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, celena_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Shoe_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_2_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_ALPHA, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 60456),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Butt_mesh_layer_5_mat_override_Metal__METAL__0),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 70, -1, 0, celena_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Torso_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 122, -12, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_5_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Half_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Left),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Right),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Up),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Down),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Head_Dead),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Capless_Head),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 53, 0, 75, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Arm_Color_mesh_layer_5_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, celena_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Forearm_mesh_layer_5_mat_override_Metal__METAL__0),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, 28, -21, 25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Wing_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Arm_Color_mesh_layer_5_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 0, celena_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Forearm_mesh_layer_5_mat_override_Metal__METAL__0),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Open),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Peace),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Cap),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_celena_Right_Hand_Wing_Cap),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, -28, 21, -25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Wing_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, 45, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Thigh_Color_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, celena_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, celena_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, -46, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Thigh_Color_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, celena_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Left_Switch_Option_Head_Left_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Right_Switch_Option_Head_Right_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Up_Switch_Option_Head_Up_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Down_Switch_Option_Head_Down_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Left),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Right),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Up),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Down),
			GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head_jump_celena_Capless_Head_Switch_Option_Capless_Head_Dead),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_2_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_2_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 60456),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Butt_mesh_layer_5_mat_override_Metal__METAL__0),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 70, -1, 0, celena_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Torso_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 122, -12, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_5_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Half_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Closed),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Left),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Right),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Up),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Down),
												GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Head_Dead),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Capless_Head),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 53, 0, 75, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Arm_Color_mesh_layer_5_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, celena_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Forearm_mesh_layer_5_mat_override_Metal__METAL__0),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, 28, -21, 25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Wing_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, -74, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Arm_Color_mesh_layer_5_mat_override_Metal__METAL__0),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 66, 0, 0, celena_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Forearm_mesh_layer_5_mat_override_Metal__METAL__0),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Open),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Peace),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Cap),
											GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_celena_Right_Hand_Wing_Cap),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, -28, 21, -25, -137),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Wing_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, 45, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Thigh_Color_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, celena_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 6, 0, celena_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, -46, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, celena_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Thigh_Color_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, celena_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout celena_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 17201),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SCALE(LAYER_OPAQUE, 60456),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Butt_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Butt_mesh_layer_5),
											GEO_ASM(0, geo_move_mario_part_from_parent),
											GEO_ASM(0, geo_mario_tilt_torso),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 70, -1, 0, celena_Torso_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Torso_mesh_layer_5),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 122, -12, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_head_rotation),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Head_DL_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Head_DL_mesh_layer_5),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, celena_Head_Half_Closed),
																		GEO_BRANCH(1, celena_Head_Closed),
																		GEO_BRANCH(1, celena_Head_Left),
																		GEO_BRANCH(1, celena_Head_Right),
																		GEO_BRANCH(1, celena_Head_Up),
																		GEO_BRANCH(1, celena_Head_Down),
																		GEO_BRANCH(1, celena_Head_Dead),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, celena_Capless_Head),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 53, 0, 75, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Arm_Color_mesh_layer_5),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, celena_Left_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Forearm_mesh_layer_5),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Left_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, celena_Left_Hand_Open),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, 28, -21, 25, -137),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Wing_DL_mesh_layer_5),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, -74, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Arm_Color_mesh_layer_5),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 0, celena_Right_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Forearm_mesh_layer_5),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, celena_Right_Hand_Open),
																	GEO_BRANCH(1, celena_Right_Hand_Peace),
																	GEO_BRANCH(1, celena_Right_Hand_Cap),
																	GEO_BRANCH(1, celena_Right_Hand_Wing_Cap),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_FORCE, 15, -32, -28, 21, -25, -137),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Wing_DL_mesh_layer_5),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, 45, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Left_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Thigh_Color_mesh_layer_5),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Left_Leg_skinned_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_skinned_mesh_layer_5),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, celena_Left_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Left_Leg_mesh_layer_5),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, celena_Left_Shoe_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 6, -46, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, celena_Right_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Thigh_Color_mesh_layer_5),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Leg_skinned_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_skinned_mesh_layer_5),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, celena_Right_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_Right_Leg_mesh_layer_5),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 6, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_Right_Shoe_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, celena_B_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, celena_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, celena_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, celena_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, celena_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
